title: Theo Acquah
logo: assets/profile_photo.png
description:  "Business & Data Analytics professional turning complex enterprise data into decision-ready insights using SQL, Tableau, Python & Oracle Cloud PPM."
show_downloads: false
theme: jekyll-theme-minimal
