title: Theo Acquah
logo: assets/profile_photo.png
# description: Executive Project Portfolio Decision Intelligence using Tableau, synthetic Oracle PPM-style data, and an evidence-to-action framework.
show_downloads: false
theme: jekyll-theme-minimal
